=== PolitecnicoJIC-SO/Taller01-Ejercicio05/Ejercicio 5.dtd
<!ELEMENT listaCompras (venta+)>
<!ELEMENT venta (ventaCredito|ventaInmediata)>
<!ELEMENT ventaCredito (fechaFinPago?, cantidad)>
<!ELEMENT ventaInmediata (cantidad, divisa)>
<!ELEMENT fechaFinPago (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT divisa (#PCDATA)>

=== PolitecnicoJIC-SO/Taller01-Ejercicio05/Ejercicio 5.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE listaCompras SYSTEM "Ejercicio 5.dtd"> -->

<listaCompras xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio 5.xsd">

    <venta>
        <ventaCredito>
            <fechaFinPago>01-07-2022</fechaFinPago>
            <cantidad>1500000</cantidad>
        </ventaCredito>
    </venta>

    <venta>
        <ventaCredito>
            <cantidad>4000</cantidad>
        </ventaCredito>
    </venta>

    <venta>
        <ventaInmediata>
            <cantidad>50</cantidad>
            <divisa>Dolares</divisa>
        </ventaInmediata>
    </venta>

</listaCompras>
